# Generated by Django 3.0.3 on 2020-08-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200806_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
